# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2707ce698bfc6241cdfc51e11419849b6ff739db53a9836899693e0890cf9796ac1012788f8b1057ca38871350d318efd1fb442ec5352cb4364c048e89ed2e

test:
  secret_key_base: e4b0da66da3aa584646d9ce6b95f9581a1da9ee6cb7c3c4330b3a55cbfd1015cd312ed58347c2a8fddb91219b4cfb60b7e37f65aea743bb0900a23f9cacd29d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
